// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_B7ArJu2Bja8juKHei4RFYlCx1lfmWR4',
    appId: '1:903043312093:web:ca8702d7bb548ed02aae34',
    messagingSenderId: '903043312093',
    projectId: 'home-haven-dc521',
    authDomain: 'home-haven-dc521.firebaseapp.com',
    storageBucket: 'home-haven-dc521.firebasestorage.app',
    measurementId: 'G-S1MQW1DYBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX4wsJVrOxyrSun_FmZcXpMQNoQ0a6YWw',
    appId: '1:903043312093:android:7842fcc6ca9b6b042aae34',
    messagingSenderId: '903043312093',
    projectId: 'home-haven-dc521',
    storageBucket: 'home-haven-dc521.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj7tKhFEL7y-ew49qQplujKNwmegk89M0',
    appId: '1:903043312093:ios:c298c8207f032ec32aae34',
    messagingSenderId: '903043312093',
    projectId: 'home-haven-dc521',
    storageBucket: 'home-haven-dc521.firebasestorage.app',
    iosBundleId: 'com.example.homehaven',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_B7ArJu2Bja8juKHei4RFYlCx1lfmWR4',
    appId: '1:903043312093:web:f5bc38916a018d892aae34',
    messagingSenderId: '903043312093',
    projectId: 'home-haven-dc521',
    authDomain: 'home-haven-dc521.firebaseapp.com',
    storageBucket: 'home-haven-dc521.firebasestorage.app',
    measurementId: 'G-8Y6BE4X0T8',
  );
}
